use_frameworks!

target 'SceneKitShapes_iOS' do
  platform :ios, '11.0'
  pod 'SceneKitShapes', :path => '../'
  project 'SceneKitShapes_iOS.xcodeproj'
  workspace 'SceneKitShapesExample.xcworkspace'

end


target 'SceneKitShapes_MacOS' do
  platform :osx, '10.13'
  pod 'SceneKitShapes', :path => '../'
  project 'SceneKitShapes_MacOS.xcodeproj'
  workspace 'SceneKitShapesExample.xcworkspace'

end
